
DROP TABLE IF EXISTS footballers CASCADE;

CREATE TABLE footballers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  nationality VARCHAR(255) NOT NULL,
  flag_img VARCHAR(255) NOT NULL,
  league VARCHAR(255) NOT NULL,
  team VARCHAR(255) NOT NULL,
  team_img VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  number INTEGER NOT NULL,
  age INTEGER NOT NULL,
  image VARCHAR(255) NOT NULL
);
