INSERT INTO footballers ( name, league, team, position, number, nationality, age, image) VALUES
('Bruno Fernandes', 'Premier League', 'Manchester United', 'Midfielder', 8, 'Portugal', 29, 'https://cdn.soccerwiki.org/images/player/64598.png'),
('Erling Haaland', 'Premier League', 'Manchester City', 'Forward', 9, 'Norway', 21, 'https://cdn.soccerwiki.org/images/player/88100.png'),
('Mohamed Salah', 'Premier League', 'Liverpool', 'Forward', 11, 'Egypt', 29, 'https://cdn.soccerwiki.org//images//player//52690.png'),
('Dominic Solanke', 'Premier League', 'Bournemouth', 'Forward', 9, 'England', 24, 'https://cdn.soccerwiki.org/images/player/76281.png'),
('Son Heung-min', 'Premier League', 'Tottenham Hotspur', 'Forward', 7, 'South Korea', 29, 'https://cdn.soccerwiki.org/images/player/45279.png'),
('Jarrod Bowen', 'Premier League', 'West Ham United', 'Forward', 20, 'England', 25, 'https://cdn.soccerwiki.org/images/player/73249.png'),
('Ollie Watkins', 'Premier League', 'Aston Villa', 'Forward', 11, 'England', 26, 'https://cdn.soccerwiki.org/images/player/76517.png'),
('Kieran Trippier', 'Premier League', 'Newcastle United', 'Defender', 23, 'England', 31, 'https://cdn.soccerwiki.org/images/player/45675.png'),
('Pedro Neto', 'Premier League', 'Wolverhampton Wanderers', 'Forward', 7, 'Portugal', 21, 'https://cdn.soccerwiki.org/images/player/91278.png'),
('Bukayo Saka', 'Premier League', 'Arsenal', 'Midfielder', 7, 'England', 22, 'https://cdn.soccerwiki.org/images/player/99607.png'),
('Darwin Nunez', 'Premier League', 'Liverpool', 'Forward', 9, 'Uruguay', 24, 'https://cdn.soccerwiki.org/images/player/95052.png'),
('James Ward-Prowse', 'Premier League', 'West Ham United', 'Midfielder', 7, 'England', 29, 'https://cdn.soccerwiki.org/images/player/53464.png'),
('Julian Alvarez', 'Premier League', 'Manchester City', 'Midfielder', 19, 'Argentina', 23, 'https://cdn.soccerwiki.org/images/player/99727.png'),
('Pedro Porro', 'Premier League', 'Tottenham Hotspur', 'Defender', 23, 'Spain', 24, 'https://cdn.soccerwiki.org/images/player/94161.png'),
('Phil Foden', 'Premier League', 'Manchester City', 'Midfielder', 47, 'England', 23, 'https://cdn.soccerwiki.org/images/player/89018.png'),
('Mario Lemina', 'Premier League', 'Wolverhampton Wanderers', 'Midfielder', 5, 'Gabon', 30, 'https://cdn.soccerwiki.org/images/player/64397.png'),
('Anthony Gordon', 'Premier League', 'Newcastle United', 'Forward', 10, 'England', 22, 'https://cdn.soccerwiki.org/images/player/94350.png'),
('Emerson Palmieri', 'Premier League', 'West Ham United', 'Defender', 33, 'Italy', 29, 'https://cdn.soccerwiki.org/images/player/59673.png'),
('Harry Kane', 'Premier League', 'Bayern Munchen', 'Forward', 9, 'England', 30, 'https://cdn.soccerwiki.org/images/player/49590.png'),
('Raheem Sterling', 'Premier League', 'Chelsea', 'Forward', 7, 'England', 29, 'https://cdn.soccerwiki.org/images/player/55579.png'),
('Ruben Neves', 'Premier League', 'Al Hilal', 'Midfielder', 8, 'Portugal', 26, 'https://cdn.soccerwiki.org/images/player/74545.png'),
('Wilfried Zaha', 'Premier League', 'Galatasaray', 'Forward', 14, 'Ivory Coast', 31, 'https://cdn.soccerwiki.org/images/player/45273.png'),
('NGolo Kanté', 'Premier League', 'Al Ittihad', 'Midfielder', 7, 'France', 32, 'https://cdn.soccerwiki.org/images/player/68341.png'),
('Jamie Vardy', 'Premier League', 'Leicester City', 'Forward', 9, 'England', 35, 'https://cdn.soccerwiki.org/images/player/50913.png'),
('Jack Grealish', 'Premier League', 'Manchester City', 'Midfielder', 10, 'England', 26, 'https://cdn.soccerwiki.org/images/player/82063.png'),
('Ben White', 'Premier League', 'Arsenal', 'Defender', 4, 'England', 25, 'https://cdn.soccerwiki.org/images/player/92137.png'),
('Trent Alexander-Arnold', 'Premier League', 'Liverpool', 'Defender', 66, 'England', 23, 'https://cdn.soccerwiki.org/images/player/74655.png'),
('Mason Mount', 'Premier League', 'Chelsea', 'Midfielder', 19, 'England', 23, 'https://cdn.soccerwiki.org/images/player/86664.png'),
('Jadon Sancho', 'Premier League', 'Manchester United', 'Forward', 25, 'England', 22, 'https://cdn.soccerwiki.org/images/player/84066.png'),
('Ezri Konsa', 'Premier League', 'Aston Villa', 'Defender', 16, 'England', 24, 'https://cdn.soccerwiki.org/images/player/85362.png'),
('Jordan Henderson', 'Premier League', 'Liverpool', 'Midfielder', 14, 'England', 32, 'https://cdn.soccerwiki.org/images/player/55824.png'),
('Declan Rice', 'Premier League', 'West Ham United', 'Midfielder', 41, 'England', 23, 'https:\/\/cdn.soccerwiki.org\/images\/player\/90916.png'),
('Kyle Walker', 'Premier League', 'Manchester City', 'Defender', 2, 'England', 32, 'https://cdn.soccerwiki.org/images/player/52606.png'),
('Che Adams', 'Premier League', 'Southampton', 'Forward', 10, 'Scotland', 26, 'https://cdn.soccerwiki.org/images/player/81122.png'),
('Riyad Mahrez', 'Premier League', 'Manchester City', 'Forward', 26, 'Algeria', 31, 'https://cdn.soccerwiki.org/images/player/51372.png'),
('Kalvin Phillips', 'Premier League', 'Leeds United', 'Midfielder', 23, 'England', 26, 'https://cdn.soccerwiki.org/images/player/89463.png'),
('Michael Keane', 'Premier League', 'Everton', 'Defender', 5, 'England', 29, 'https://cdn.soccerwiki.org/images/player/55119.png'),
('Bernardo Silva', 'Premier League', 'Manchester City', 'Midfielder', 20, 'Portugal', 27, 'https://cdn.soccerwiki.org/images/player/55823.png'),
('Harry Maguire', 'Premier League', 'Manchester United', 'Defender', 5, 'England', 29, 'https://cdn.soccerwiki.org/images/player/55107.png'),
('Raphael Varane', 'Premier League', 'Manchester United', 'Defender', 19, 'France', 29, 'https://cdn.soccerwiki.org/images/player/54260.png'),
('Rúben Dias', 'Premier League', 'Manchester City', 'Defender', 3, 'Portugal', 25, 'https://cdn.soccerwiki.org/images/player/84036.png'),
('Mateo Kovacic', 'Premier League', 'Chelsea', 'Midfielder', 17, 'Croatia', 27, 'https://cdn.soccerwiki.org/images/player/55634.png'),
('Timo Werner', 'Premier League', 'Chelsea', 'Forward', 11, 'Germany', 26, 'https://cdn.soccerwiki.org/images/player/79264.png'),
('Caglar Soyuncu', 'Premier League', 'Leicester City', 'Defender', 4, 'Turkey', 26, 'https://cdn.soccerwiki.org/images/player/72140.png'),
('Emiliano Martinez', 'Premier League', 'Aston Villa', 'Goalkeeper', 26, 'Argentina', 30, 'https://cdn.soccerwiki.org/images/player/58162.png'),
('Pierre-Emerick Aubameyang', 'Premier League', 'Arsenal', 'Forward', 14, 'Gabon', 32, 'https://cdn.soccerwiki.org/images/player/55115.png'),
('Sadio Mane', 'Premier League', 'Liverpool', 'Forward', 10, 'Senegal', 30, 'https://cdn.soccerwiki.org/images/player/55076.png'),
('Christian Pulisic', 'Premier League', 'Chelsea', 'Forward', 10, 'United States', 23, 'https://cdn.soccerwiki.org/images/player/82103.png'),
('Ben Chilwell', 'Premier League', 'Chelsea', 'Defender', 21, 'England', 25, 'https://cdn.soccerwiki.org/images/player/82787.png'),
('Youri Tielemans', 'Premier League', 'Leicester City', 'Midfielder', 8, 'Belgium', 25, 'https://cdn.soccerwiki.org/images/player/73286.png'),
('Mason Holgate', 'Premier League', 'Everton', 'Defender', 2, 'England', 25, 'https://cdn.soccerwiki.org/images/player/81276.png'),
('João Cancelo', 'Premier League', 'Manchester City', 'Defender', 27, 'Portugal', 28, 'https://cdn.soccerwiki.org/images/player/56592.png'),
('Conor Gallagher', 'Premier League', 'Crystal Palace', 'Midfielder', 23, 'England', 21, 'https://cdn.soccerwiki.org/images/player/92262.png'),
('Harvey Barnes', 'Premier League', 'Leicester City', 'Forward', 15, 'England', 24, 'https://cdn.soccerwiki.org/images/player/80615.png'),
('Ezgjan Alioski', 'Premier League', 'Leeds United', 'Defender', 10, 'North Macedonia', 30, 'https://cdn.soccerwiki.org/images/player/80415.png'),
('Ferran Torres', 'Premier League', 'Manchester City', 'Forward', 21, 'Spain', 21, 'https://cdn.soccerwiki.org/images/player/91289.png'),
('Nathan Ake', 'Premier League', 'Manchester City', 'Defender', 6, 'Netherlands', 26, 'https://cdn.soccerwiki.org/images/player/70396.png'),
('Odsonne Edouard', 'Premier League', 'Crystal Palace', 'Forward', 22, 'France', 23, 'https://cdn.soccerwiki.org/images/player/91655.png'),
('Raphael Guerreiro', 'Premier League', 'Manchester United', 'Defender', 13, 'Portugal', 28, 'https://cdn.soccerwiki.org/images/player/52138.png'),
('Joel Matip', 'Premier League', 'Liverpool', 'Defender', 32, 'Cameroon', 31, 'https://cdn.soccerwiki.org/images/player/54569.png'),
('Pablo Fornals', 'Premier League', 'West Ham United', 'Midfielder', 20, 'Spain', 26, 'https://cdn.soccerwiki.org/images/player/85657.png'),
('Eduardo Camavinga', 'Premier League', 'Manchester United', 'Midfielder', 21, 'France', 19, 'https://cdn.soccerwiki.org/images/player/96361.png'),
('Ruben Loftus-Cheek', 'Premier League', 'Fulham', 'Midfielder', 12, 'England', 25, 'https://cdn.soccerwiki.org/images/player/72342.png'),
('Adam Webster', 'Premier League', 'Brighton & Hove Albion', 'Defender', 4, 'England', 27, 'https://cdn.soccerwiki.org/images/player/81420.png'),
('Andros Townsend', 'Premier League', 'Everton', 'Forward', 23, 'England', 31, 'https://cdn.soccerwiki.org/images/player/55452.png'),
('Conor Coady', 'Premier League', 'Wolverhampton Wanderers', 'Defender', 16, 'England', 29, 'https://cdn.soccerwiki.org/images/player/51715.png'),
('Moussa Sissoko', 'Premier League', 'Watford', 'Midfielder', 22, 'France', 32, 'https://cdn.soccerwiki.org/images/player/55796.png'),
('Eberechi Eze', 'Premier League', 'Crystal Palace', 'Midfielder', 25, 'England', 23, 'https://cdn.soccerwiki.org/images/player/81340.png'),
('Marcos Alonso', 'Premier League', 'Chelsea', 'Defender', 3, 'Spain', 31, 'https://cdn.soccerwiki.org/images/player/52685.png'),
('Bertrand Traoré', 'Premier League', 'Aston Villa', 'Forward', 15, 'Burkina Faso', 26, 'https://cdn.soccerwiki.org/images/player/68146.png'),
('Leandro Trossard', 'Premier League', 'Brighton & Hove Albion', 'Forward', 11, 'Belgium', 27, 'https://cdn.soccerwiki.org/images/player/78226.png'),
('Joachim Andersen', 'Premier League', 'Crystal Palace', 'Defender', 5, 'Denmark', 26, 'https://cdn.soccerwiki.org/images/player/74649.png'),
('Teemu Pukki', 'Premier League', 'Norwich City', 'Forward', 22, 'Finland', 31, 'https://cdn.soccerwiki.org/images/player/66419.png'),
('Allan Saint-Maximin', 'Premier League', 'Newcastle United', 'Forward', 10, 'France', 25, 'https://cdn.soccerwiki.org/images/player/86384.png'),
('Yves Bissouma', 'Premier League', 'Brighton & Hove Albion', 'Midfielder', 8, 'Mali', 25, 'https://cdn.soccerwiki.org/images/player/80797.png'),
('Conor Hourihane', 'Premier League', 'Aston Villa', 'Midfielder', 14, 'Ireland', 30, 'https://cdn.soccerwiki.org/images/player/58397.png'),
('Ben Mee', 'Premier League', 'Burnley', 'Defender', 6, 'England', 32, 'https://cdn.soccerwiki.org/images/player/54552.png'),
('Ryan Bertrand', 'Premier League', 'Leicester City', 'Defender', 5, 'England', 32, 'https://cdn.soccerwiki.org/images/player/53322.png'),
('Jean-Philippe Mateta', 'Premier League', 'Crystal Palace', 'Forward', 14, 'France', 25, 'https://cdn.soccerwiki.org/images/player/72009.png'),
('John McGinn', 'Premier League', 'Aston Villa', 'Midfielder', 7, 'Scotland', 28, 'https://cdn.soccerwiki.org/images/player/88190.png'),
('Chris Wood', 'Premier League', 'Newcastle United', 'Forward', 9, 'New Zealand', 30, 'https://cdn.soccerwiki.org/images/player/77576.png'),
('Ozan Kabak', 'Premier League', 'Norwich City', 'Defender', 19, 'Turkey', 22, 'https://cdn.soccerwiki.org/images/player/88785.png'),
('Serge Aurier', 'Premier League', 'Watford', 'Defender', 24, 'Ivory Coast', 29, 'https://cdn.soccerwiki.org/images/player/51588.png'),
('Pierre Lees-Melou', 'Premier League', 'Leeds United', 'Midfielder', 8, 'France', 29, 'https://cdn.soccerwiki.org/images/player/86372.png'),
('Danny Ings', 'Premier League', 'Aston Villa', 'Forward', 9, 'England', 29, 'https://cdn.soccerwiki.org/images/player/50463.png'),
('Ismaïla Sarr', 'Premier League', 'Watford', 'Forward', 23, 'Senegal', 24, 'https://cdn.soccerwiki.org/images/player/80895.png'),
('Kiernan Dewsbury-Hall', 'Premier League', 'Leicester City', 'Midfielder', 8, 'England', 23, 'https://cdn.soccerwiki.org/images/player/93889.png'),
('Adama Traoré', 'Premier League', 'Wolverhampton Wanderers', 'Forward', 37, 'Spain', 26, 'https://cdn.soccerwiki.org/images/player/71535.png'),
('Aaron Ramsdale', 'Premier League', 'Arsenal', 'Goalkeeper', 1, 'England', 23, 'https://cdn.soccerwiki.org/images/player/73897.png'),
('Leandro Bacuna', 'Premier League', 'Watford', 'Midfielder', 8, 'Curacao', 30, 'https://cdn.soccerwiki.org/images/player/64789.png'),
('Benjamin Mendy', 'Premier League', 'Burnley', 'Defender', 22, 'France', 27, 'https://cdn.soccerwiki.org/images/player/56341.png'),
('Nat Phillips', 'Premier League', 'Liverpool', 'Defender', 47, 'England', 24, 'https://cdn.soccerwiki.org/images/player/86842.png'),
('Conor Roberts', 'Premier League', 'Burnley', 'Defender', 23, 'Wales', 26, 'https://cdn.soccerwiki.org/images/player/78671.png'),
('Dennis Praet', 'Premier League', 'Leicester City', 'Midfielder', 26, 'Belgium', 27, 'https://cdn.soccerwiki.org/images/player/64188.png'),
('Lucas Digne', 'Premier League', 'Aston Villa', 'Defender', 12, 'France', 28, 'https://cdn.soccerwiki.org/images/player/61487.png'),
('Jayden Bogle', 'Premier League', 'Norwich City', 'Defender', 2, 'England', 21, 'https://cdn.soccerwiki.org/images/player/88312.png'),
('Isaac Hayden', 'Premier League', 'Newcastle United', 'Midfielder', 14, 'England', 26, 'https://cdn.soccerwiki.org/images/player/72666.png'),
('Matty Cash', 'Premier League', 'Aston Villa', 'Defender', 2, 'Poland', 24, 'https://cdn.soccerwiki.org/images/player/84232.png'),
('Adam Armstrong', 'Premier League', 'Southampton', 'Forward', 17, 'England', 25, 'https://cdn.soccerwiki.org/images/player/77468.png'),
('Rúben Neves', 'Premier League', 'Manchester United', 'Midfielder', 6, 'Portugal', 24, 'https://cdn.soccerwiki.org/images/player/73505.png');
