INSERT INTO footballers ( name, league, team, position, number, nationality, age, image) VALUES
('Bruno Fernandes', 'Premier League', 'Manchester United', 'Midfielder', 8, 'Portugal', 29, 'https://cdn.soccerwiki.org/images/player/64598.png'),
('Erling Haaland', 'Premier League', 'Manchester City', 'Forward', 9, 'Norway', 23, 'https://cdn.soccerwiki.org/images/player/88100.png'),
('Mohamed Salah', 'Premier League', 'Liverpool', 'Forward', 11, 'Egypt', 31, 'https://cdn.soccerwiki.org//images//player//52690.png'),
('Dominic Solanke', 'Premier League', 'Bournemouth', 'Forward', 9, 'England', 26, 'https://cdn.soccerwiki.org/images/player/76281.png'),
('Son Heung-min', 'Premier League', 'Tottenham Hotspur', 'Forward', 7, 'South Korea', 31, 'https://cdn.soccerwiki.org/images/player/45279.png'),
('Jarrod Bowen', 'Premier League', 'West Ham United', 'Forward', 20, 'England', 27, 'https://cdn.soccerwiki.org/images/player/73249.png'),
('Ollie Watkins', 'Premier League', 'Aston Villa', 'Forward', 11, 'England', 28, 'https://cdn.soccerwiki.org/images/player/76517.png'),
('Kieran Trippier', 'Premier League', 'Newcastle United', 'Defender', 2, 'England', 33, 'https://cdn.soccerwiki.org/images/player/45675.png'),
('Pedro Neto', 'Premier League', 'Wolverhampton Wanderers', 'Forward', 7, 'Portugal', 23, 'https://cdn.soccerwiki.org/images/player/91278.png'),
('Bukayo Saka', 'Premier League', 'Arsenal', 'Midfielder', 7, 'England', 22, 'https://cdn.soccerwiki.org/images/player/99607.png'),
('Darwin Nunez', 'Premier League', 'Liverpool', 'Forward', 9, 'Uruguay', 24, 'https://cdn.soccerwiki.org/images/player/95052.png'),
('James Ward-Prowse', 'Premier League', 'West Ham United', 'Midfielder', 7, 'England', 29, 'https://cdn.soccerwiki.org/images/player/53464.png'),
('Julian Alvarez', 'Premier League', 'Manchester City', 'Midfielder', 19, 'Argentina', 23, 'https://cdn.soccerwiki.org/images/player/99727.png'),
('Pedro Porro', 'Premier League', 'Tottenham Hotspur', 'Defender', 23, 'Spain', 24, 'https://cdn.soccerwiki.org/images/player/94161.png'),
('Phil Foden', 'Premier League', 'Manchester City', 'Midfielder', 47, 'England', 23, 'https://cdn.soccerwiki.org/images/player/89018.png'),
('Mario Lemina', 'Premier League', 'Wolverhampton Wanderers', 'Midfielder', 5, 'Gabon', 30, 'https://cdn.soccerwiki.org/images/player/64397.png'),
('Anthony Gordon', 'Premier League', 'Newcastle United', 'Forward', 10, 'England', 22, 'https://cdn.soccerwiki.org/images/player/94350.png'),
('Emerson Palmieri', 'Premier League', 'West Ham United', 'Defender', 33, 'Italy', 29, 'https://cdn.soccerwiki.org/images/player/59673.png'),
('Harry Kane', 'Premier League', 'Bayern Munchen', 'Forward', 9, 'England', 30, 'https://cdn.soccerwiki.org/images/player/49590.png'),
('Raheem Sterling', 'Premier League', 'Chelsea', 'Forward', 7, 'England', 29, 'https://cdn.soccerwiki.org/images/player/55579.png'),
('Ruben Neves', 'Premier League', 'Al Hilal', 'Midfielder', 8, 'Portugal', 26, 'https://cdn.soccerwiki.org/images/player/74545.png'),
('Wilfried Zaha', 'Premier League', 'Galatasaray', 'Forward', 14, 'Ivory Coast', 31, 'https://cdn.soccerwiki.org/images/player/45273.png'),
('NGolo Kanté', 'Premier League', 'Al Ittihad', 'Midfielder', 7, 'France', 32, 'https://cdn.soccerwiki.org/images/player/68341.png'),
('Jamie Vardy', 'Premier League', 'Leicester City', 'Forward', 9, 'England', 37, 'https://cdn.soccerwiki.org/images/player/53822.png'),
('Jack Grealish', 'Premier League', 'Manchester City', 'Midfielder', 10, 'England', 28, 'https://cdn.soccerwiki.org/images/player/70608.png'),
('Ben White', 'Premier League', 'Arsenal', 'Defender', 4, 'England', 26, 'https://cdn.soccerwiki.org/images/player/87633.png'),
('Trent Alexander-Arnold', 'Premier League', 'Liverpool', 'Defender', 66, 'England', 25, 'https://cdn.soccerwiki.org/images/player/88385.png'),
('Mason Mount', 'Premier League', 'Manchester United', 'Midfielder', 7, 'England', 25, 'https://cdn.soccerwiki.org/images/player/90932.png'),
('Jadon Sancho', 'Premier League', 'Manchester United', 'Forward', 25, 'England', 23, 'https://cdn.soccerwiki.org/images/player/90936.png'),
('Ezri Konsa', 'Premier League', 'Aston Villa', 'Defender', 4, 'England', 26, 'https://cdn.soccerwiki.org/images/player/89371.png'),
('Jordan Henderson', 'Premier League', 'Al Ettifaq', 'Midfielder', 10, 'England', 33, 'https://cdn.soccerwiki.org/images/player/36211.png'),
('Declan Rice', 'Premier League', 'Arsenal', 'Midfielder', 41, 'England', 24, 'https://cdn.soccerwiki.org/images/player/90916.png'),
('Kyle Walker', 'Premier League', 'Manchester City', 'Defender', 2, 'England', 33, 'https://cdn.soccerwiki.org/images/player/37853.png'),
('Che Adams', 'Premier League', 'Southampton', 'Forward', 10, 'Scotland', 27, 'https://cdn.soccerwiki.org/images/player/79506.png'),
('Riyad Mahrez', 'Premier League', 'Al Ahli Sfc', 'Forward', 7, 'Algeria', 32, 'https://cdn.soccerwiki.org/images/player/58616.png'),
('Kalvin Phillips', 'Premier League', 'Manchester City', 'Midfielder', 4, 'England', 28, 'https://cdn.soccerwiki.org/images/player/80933.png'),
('Michael Keane', 'Premier League', 'Everton', 'Defender', 5, 'England', 31, 'https://cdn.soccerwiki.org/images/player/53288.png'),
('Bernardo Silva', 'Premier League', 'Manchester City', 'Midfielder', 20, 'Portugal', 29, 'https://cdn.soccerwiki.org/images/player/68182.png'),
('Harry Maguire', 'Premier League', 'Manchester United', 'Defender', 5, 'England', 30, 'https://cdn.soccerwiki.org/images/player/51661.png'),
('Raphael Varane', 'Premier League', 'Manchester United', 'Defender', 19, 'France', 30, 'https://cdn.soccerwiki.org/images/player/47392.png'),
('Rúben Dias', 'Premier League', 'Manchester City', 'Defender', 3, 'Portugal', 26, 'https://cdn.soccerwiki.org/images/player/85994.png'),
('Mateo Kovacic', 'Premier League', 'Manchester City', 'Midfielder', 8, 'Croatia', 29, 'https://cdn.soccerwiki.org/images/player/47427.png'),
('Timo Werner', 'Premier League', 'Tottenhem Hotspur', 'Forward', 16, 'Germany', 27, 'https://cdn.soccerwiki.org/images/player/67935.png'),
('Caglar Soyuncu', 'Premier League', 'Atletico Madrid', 'Defender', 4, 'Turkey', 27, 'https://cdn.soccerwiki.org/images/player/84912.png'),
('Emiliano Martinez', 'Premier League', 'Aston Villa', 'Goalkeeper', 1, 'Argentina', 31, 'https://cdn.soccerwiki.org/images/player/61102.png'),
('Pierre-Emerick Aubameyang', 'Premier League', 'Olimpique Marseille', 'Forward', 10, 'Gabon', 34, 'https://cdn.soccerwiki.org/images/player/34634.png'),
('Sadio Mane', 'Premier League', 'Al Nassr', 'Forward', 10, 'Senegal', 31, 'https://cdn.soccerwiki.org/images/player/56394.png'),
('Christian Pulisic', 'Premier League', 'Ac Milan', 'Forward', 11, 'United States', 25, 'https://cdn.soccerwiki.org/images/player/85046.png'),
('Ben Chilwell', 'Premier League', 'Chelsea', 'Defender', 21, 'England', 27, 'https://cdn.soccerwiki.org/images/player/82015.png'),
('Youri Tielemans', 'Premier League', 'Aston Villa', 'Midfielder', 8, 'Belgium', 26, 'https://cdn.soccerwiki.org/images/player/67729.png'),
('Mason Holgate', 'Premier League', 'Southampton', 'Defender', 6, 'England', 6, 'https://cdn.soccerwiki.org/images/player/80068.png'),
('João Cancelo', 'Premier League', 'Barcelona', 'Defender', 2, 'Portugal', 29, 'https://cdn.soccerwiki.org/images/player/59016.png'),
('Conor Gallagher', 'Premier League', 'Chelsea', 'Midfielder', 23, 'England', 23, 'https://cdn.soccerwiki.org/images/player/101784.png'),
('Harvey Barnes', 'Premier League', 'Newcastle united', 'Forward', 15, 'England', 26, 'https://cdn.soccerwiki.org/images/player/89008.png'),
('Ezgjan Alioski', 'Premier League', 'Al Ahli Sfc', 'Defender', 11, 'North Macedonia', 31, 'https://cdn.soccerwiki.org/images/player/52841.png'),
('Ferran Torres', 'Premier League', 'Barcelona', 'Forward', 7, 'Spain', 23, 'https://cdn.soccerwiki.org/images/player/93445.png'),
('Nathan Ake', 'Premier League', 'Manchester City', 'Defender', 6, 'Netherlands', 28, 'https://cdn.soccerwiki.org/images/player/64626.png'),
('Odsonne Edouard', 'Premier League', 'Crystal Palace', 'Forward', 22, 'France', 25, 'https://cdn.soccerwiki.org/images/player/83508.png'),
('Raphael Guerreiro', 'Premier League', 'Bayern Munchen', 'Defender', 22, 'Portugal', 30, 'https://cdn.soccerwiki.org/images/player/59500.png'),
('Joel Matip', 'Premier League', 'Liverpool', 'Defender', 32, 'Cameroon', 32, 'https://cdn.soccerwiki.org/images/player/42549.png'),
('Pablo Fornals', 'Premier League', 'West Ham United', 'Midfielder', 8, 'Spain', 27, 'https://cdn.soccerwiki.org/images/player/84483.png'),
('Eduardo Camavinga', 'Premier League', 'Real Madrid', 'Midfielder', 12, 'France', 21, 'https://cdn.soccerwiki.org/images/player/101125.png'),
('Ruben Loftus-Cheek', 'Premier League', 'Ac Milan', 'Midfielder', 8, 'England', 27, 'https://cdn.soccerwiki.org/images/player/78753.png'),
('Adam Webster', 'Premier League', 'Brighton & Hove Albion', 'Defender', 4, 'England', 29, 'https://cdn.soccerwiki.org/images/player/55099.png'),
('Andros Townsend', 'Premier League', 'Luton Town', 'Forward', 30, 'England', 32, 'https://cdn.soccerwiki.org/images/player/38646.png'),
('Conor Coady', 'Premier League', 'Leicester City', 'Defender', 4, 'England', 30, 'https://cdn.soccerwiki.org/images/player/63625.png'),
('Moussa Sissoko', 'Premier League', 'Fc Nantes', 'Midfielder', 17, 'France', 34, 'https://cdn.soccerwiki.org/images/player/28904.png'),
('Eberechi Eze', 'Premier League', 'Crystal Palace', 'Midfielder', 10, 'England', 25, 'https://cdn.soccerwiki.org/images/player/90783.png'),
('Marcos Alonso', 'Premier League', 'Barcelona', 'Defender', 17, 'Spain', 33, 'https://cdn.soccerwiki.org/images/player/42031.png'),
('Bertrand Traoré', 'Premier League', 'Aston Villa', 'Forward', 9, 'Burkina Faso', 28, 'https://cdn.soccerwiki.org/images/player/67570.png'),
('Leandro Trossard', 'Premier League', 'Arsenal', 'Forward', 19, 'Belgium', 29, 'https://cdn.soccerwiki.org/images/player/56415.png'),
('Joachim Andersen', 'Premier League', 'Crystal Palace', 'Defender', 16, 'Denmark', 27, 'https://cdn.soccerwiki.org/images/player/71255.png'),
('Teemu Pukki', 'Premier League', 'Minnesota United', 'Forward', 22, 'Finland', 33, 'https://cdn.soccerwiki.org/images/player/14151.png'),
('Allan Saint-Maximin', 'Premier League', 'Al Ahli Sfc', 'Forward', 10, 'France', 26, 'https://cdn.soccerwiki.org/images/player/69634.png'),
('Yves Bissouma', 'Premier League', 'Tottenhem Hotspur', 'Midfielder', 8, 'Mali', 27, 'https://cdn.soccerwiki.org/images/player/88886.png'),
('Conor Hourihane', 'Premier League', 'Derby County', 'Midfielder', 4, 'Ireland', 32, 'https://cdn.soccerwiki.org/images/player/48822.png'),
('Ben Mee', 'Premier League', 'Brentford', 'Defender', 16, 'England', 34, 'https://cdn.soccerwiki.org/images/player/45936.png'),
('Ryan Bertrand', 'Premier League', 'Leicester City', 'Defender', 5, 'England', 32, 'https://cdn.soccerwiki.org/images/player/53322.png'),
('Jean-Philippe Mateta', 'Premier League', 'Crystal Palace', 'Forward', 14, 'France', 25, 'https://cdn.soccerwiki.org/images/player/45936.png'),
('John McGinn', 'Premier League', 'Aston Villa', 'Midfielder', 7, 'Scotland', 29, 'https://cdn.soccerwiki.org/images/player/63650.png'),
('Chris Wood', 'Premier League', 'Nottingham Forest', 'Forward', 11, 'New Zealand', 32, 'https://cdn.soccerwiki.org/images/player/39821.png'),
('Ozan Kabak', 'Premier League', 'TSG 1899 Hoffenheim', 'Defender', 5, 'Turkey', 23, 'https://cdn.soccerwiki.org/images/player/99093.png'),
('Serge Aurier', 'Premier League', 'Nottingham Forest', 'Defender', 24, 'Ivory Coast', 31, 'https://cdn.soccerwiki.org/images/player/44112.png'),
('Pierre Lees-Melou', 'Premier League', 'Stage Brestois 29', 'Midfielder', 20, 'France', 30, 'https://cdn.soccerwiki.org/images/player/82753.png'),
('Danny Ings', 'Premier League', 'West Han United', 'Forward', 9, 'England', 31, 'https://cdn.soccerwiki.org/images/player/50001.png'),
('Ismaïla Sarr', 'Premier League', 'Olympique Marseille', 'Forward', 23, 'Senegal', 25, 'https://cdn.soccerwiki.org/images/player/87576.png'),
('Kiernan Dewsbury-Hall', 'Premier League', 'Leicester City', 'Midfielder', 22, 'England', 25, 'https://cdn.soccerwiki.org/images/player/103884.png'),
('Adama Traoré', 'Premier League', 'Fulham', 'Forward', 11, 'Spain', 27, 'https://cdn.soccerwiki.org/images/player/68991.png'),
('Aaron Ramsdale', 'Premier League', 'Arsenal', 'Goalkeeper', 1, 'England', 25, 'https://cdn.soccerwiki.org/images/player/90918.png'),
('Leandro Bacuna', 'Premier League', 'FC Groningen', 'Midfielder', 8, 'Curacao', 32, 'https://cdn.soccerwiki.org/images/player/42614.png'),
('Benjamin Mendy', 'Premier League', 'FC Lorient', 'Defender', 5, 'France', 29, 'https://cdn.soccerwiki.org/images/player/53471.png'),
('Nat Phillips', 'Premier League', 'Liverpool', 'Defender', 47, 'England', 26, 'https://cdn.soccerwiki.org/images/player/98235.png'),
('Conor Roberts', 'Premier League', 'Burnley', 'Defender', 14, 'Wales', 28, 'https://cdn.soccerwiki.org/images/player/83312.png'),
('Dennis Praet', 'Premier League', 'Leicester City', 'Midfielder', 26, 'Belgium', 29, 'https://cdn.soccerwiki.org/images/player/52568.png'),
('Lucas Digne', 'Premier League', 'Aston Villa', 'Defender', 12, 'France', 30, 'https://cdn.soccerwiki.org/images/player/53624.png'),
('Jayden Bogle', 'Premier League', 'Sheffield United', 'Defender', 20, 'England', 23, 'https://cdn.soccerwiki.org/images/player/97241.png'),
('Isaac Hayden', 'Premier League', 'Newcastle United', 'Midfielder', 11, 'England', 28, 'https://cdn.soccerwiki.org/images/player/68702.png'),
('Matty Cash', 'Premier League', 'Aston Villa', 'Defender', 2, 'Poland', 26, 'https://cdn.soccerwiki.org/images/player/87598.png'),
('Adam Armstrong', 'Premier League', 'Southampton', 'Forward', 9, 'England', 26, 'https://cdn.soccerwiki.org/images/player/73341.png'),
('Jack Stephens', 'Premier League', 'Southampton', 'Midfielder', 5, 'England', 29, 'https://cdn.soccerwiki.org/images/player/46671.png');
